/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataPanel: typeof import('./src/components/DataPanel.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    ImagePreview: typeof import('./src/components/ImagePreview.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    LogoTitle: typeof import('./src/components/LogoTitle.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Panel: typeof import('primevue/panel')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenshot: typeof import('./src/components/Screenshot.vue')['default']
    ScreenshotViewer: typeof import('./src/components/ScreenshotViewer.vue')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TradesTable: typeof import('./src/components/TradesTable.vue')['default']
    TradingAccounts: typeof import('./src/components/TradingAccounts.vue')['default']
    TradingAccountSelector: typeof import('./src/components/TradingAccountSelector.vue')['default']
    UploadScreenshot: typeof import('./src/components/UploadScreenshot.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
